var dam_data = [
{Name: "Adavinainarkovil Dam", River: "Thamirabarani", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Amaravathi Dam", River: "Amaravati", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Anaikuttam Dam", River: "Arjuna Nadhi", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Andiappanur Odai Dam", River: "Pambar", Location: "Vellore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Avalanche Dam", River: "Avalanche & Emerald Streams", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Barur Dam", River: "Barur", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Chinnar Dam", River: "Chinnar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Chittar I Dam", River: "Chittar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Chittar II Dam", River: "Chittar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Varahapallam dam", River: "varahapallam", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Emerald Dam", River: "Emerald", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Eravangalar Dam", River: "Eravangalar", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Gatana Dam", River: "Gatana nadhi", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Glenmorgan Forbay Dam", River: "Glenmorgan St", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Golwarpatti Dam", River: "Arujuna & Gowsiha", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Gomukhinadi Dam", River: "Gomukhinadhi", Location: "Viluppuram", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Gundar Dam", River: "Gundar", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Highwavys Dam", River: "Highwavys St.", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Irukkangudi Dam", River: "Vaippar, Arjuna", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kadamparai Dam", River: "Kadambarai", Location: "Coimbatore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kamraju Sagar Dam", River: "Sandynallah", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kariakoil Dam", River: "Kariakovil", Location: "Salem", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Karuppanadhi Dam", River: "Karuppanadhi", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kelavarapalli Dam", River: "Ponniar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kesarigulihalla Dam", River: "K.gulihalla", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kodaganar Dam", River: "~~~~~", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kodumudiyar Dam", River: "Nambiyar", Location: "Nanguneri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Krishnagiri Dam", River: "Ponniar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kullursandai Dam", River: "Vaippar", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kundah Palam Dam", River: "Kundah", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kunderipallam Dam", River: "Kunderipallam", Location: "Erode", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kuppanatham Dam", River: "Cheyyar", Location: "Tiruvannamalai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kuthiraiyar Dam", River: "Kuthiraiyar", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kuttiyar Dam", River: "Kuttiyar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Lower Bhavani Dam", River: "Bhavani", Location: "Erode", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Lower Kodayar Dam", River: "Kodayar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Lower Nirar Dam", River: "Nirar", Location: "Coimbatore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manalar Dam", River: "Manalar", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manimukthanadhi Dam", River: "Manimuktha", Location: "Viluppuram", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manimuthar Dam", River: "Manimuthur", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manjalar Dam", River: "Manjalar", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Maravakandi Forbay Dam", River: "Aravarihalla", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Marudhanadi Dam", River: "Maurdhanadhi", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mettur Dam", River: "Kaveri", Location: "Salem", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mirugandanadhi Dam", River: "~~~~~", Location: "Tiruvannamalai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mordhana Dam", River: "Koundanyanadhi", Location: "Vellore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Moyar Forebay Dam", River: "~~~~~", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mukurthy Dam", River: "Mukurthi", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nagavathi Dam", River: "Nagavathy", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nallathangal Odai Dam", River: "Nallathangal Odai", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nambiar Dam", River: "Nambiar", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nanganjiyar Dam", River: "Nanganjiyar", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nilayur Bed Dam", River: "Vagai", Location: "Madurai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Noyyal Athupalayam Dam", River: "Noyyal", Location: "Karur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Noyyal Orathupalayam Dam", River: "Noyyal", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Palar Porundalar Dam", River: "PalarPorundalar", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Pambar Dam", River: "Pambar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Papanasam Dam", River: "Thambraparani", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Parappalar Dam", River: "Parappalar", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Parson's Valley Dam", River: "Parson Valley Stream", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Pechiparai Dam", River: "Kodaiyar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Pegumbahallah Forebay Dam", River: "Pengumbahallh", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Perumpallam Dam", River: "Perumpalam", Location: "Erode", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Perunchani Dam", River: "Paralayar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Pilavukkal Kovilar Dam", River: "Kovilar", Location: "Madurai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Pilavukkal Periyar Dam", River: "Periyar", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Pillur Dam", River: "Bhavani", Location: "Coimbatore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Poigaiyar Dam", River: "Poigai", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Ponnaniar Dam", River: "Ponnaniyar", Location: "Karur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Poondi Dam", River: "Kosasthalaiyar", Location: "Thiruvallur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Porthimund Dam", River: "Porthimund St", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Puthen Dam", River: "Kodayar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Pykara Dam", River: "~~~~~", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Rajathope Kanar Dam", River: "Rajathopekanar", Location: "Chittoor", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Ramanadhi Dam", River: "Ramanadhi", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Sathanur Dam", River: "Ponniar", Location: "Tiruvannamalai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Sathiyar Dam", River: "Sathaiyaru", Location: "Madurai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Servalar Dam", River: "Servalar/ Tambiraparani", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Shanmuganadhi Dam", River: "~~~~~", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Shenbagathope Dam", River: "Kamandalar", Location: "Tiruvannamalai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Sholayar Dam", River: "Sholayar", Location: "Coimbatore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Shoolagiri Chinnar Dam", River: "Shoolagiri Chinnar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Siddhamalli Dam", River: "~~~~~", Location: "Ariyalur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Sothupparai Dam", River: "Varaganadhi", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Thirumurthi Dam", River: "Palar", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Thoppaiyar Dam", River: "Thoppaiyar", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Thumblahalli Dam", River: "Pulapatti", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Uppar(Erode) Dam", River: "Uppar", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Upper Aliyar Dam", River: "Aliyar", Location: "Coimbatore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Upper Bhavani Dam", River: "Bhavani", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Upper Kodayar Dam", River: "Kodayar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Vadakku Paichaiyar Dam", River: "Vadakkupaichaiyar", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Vaigai Dam", River: "Vaigai", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Vaniar Dam", River: "Vaniar", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Varadhamanadhi Dam", River: "Varadhamanadhi", Location: "Dindugal Anna", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Varattar Dam", River: "~~~~~", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Varattupallam Dam", River: "Varattupallam", Location: "Erode", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Vattamalaikarai Odai Dam", River: "V.K. Odai", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Vembakottai Dam", River: "~~~~~", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Vennir-Ar Dam", River: "Vennirar", Location: "idukki", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Vidur Dam", River: "Varahanadi", Location: "Viluppuram", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "West Varahapallam Weir Dam", River: "W.V.Pallam", Location: "Nilgiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Western Catchment I Dam", River: "Arickyampuzha", Location: "Nilgiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Western Catchment II Dam", River: "Karampuzha", Location: "Nilgiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Western Catchment III Dam", River: "Karampuzha", Location: "Nilgiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Willington Dam", River: "vellaru", Location: "Cuddalore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Thervoy Kandigai Dam", River: "Krishna", Location: "Tiruvallur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Visvakudi Dam", River: "Kallar", Location: "Perambalur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kottarai Dam", River: "Maruthaiyar", Location: "Perambalur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}}
]
